# -*- coding: utf-8 -*-
"""Unemployment analysis with python internship task 2 for oasis infobyte

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VJ0-H_FlAuItX0rNtGZFWfKmoIvIdMFj
"""

import numpy as np
import pandas as pd

df=pd.read_csv("/Unemployment in India.csv")

df.head()

df.tail()

"""**#returns tuple of shape (rows and columns) of dataframe**

"""

df.shape

"""#prints information about the dataframe"""

df.info()

"""**#returns numerical description of the data in the dataframe**"""

df.describe()

"""#plotting columns Region on x-axis"""

x = df['Region']
x

"""**#plotting column Estimated unemployment rate (%) on y-axis**"""

y=df[' Estimated Unemployment Rate (%)']
y

df2=df.iloc[:,3]
df2

"""Import Necessary Libraries"""

import plotly.express as px
import matplotlib.pyplot as plt

"""Analyzing Data By Bar Graphs"""

fg = px.bar(df,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
            title='Unemployment Rate (State Wise) by Bar Graph',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

fg = px.bar(df,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
            title='Unemploymeny Rate (Region Wise) by Bar Graph',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

"""Analyzing Data By Box Plot"""

fg = px.box(df,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
            title='Unemployment Rate (State Wise) by Box Plot',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

"""Analyzing Data By Scatter Plot"""

fg = px.box(df,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
            title='Unemployment Rate (State Wise) by Scatter Plot',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

"""Analyzing Data By Histogram"""

fg = px.histogram(df,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
                  title='Unemployment Rate (Statewise) by Histogram',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()





